### ISSUE TITLE
parsing a snippet of html does not seem to be working

### ISSUE THREAD

**Issue by btrem** [microformats/microformats-parser-website-node#2]
I cannot parse a snippet of html using the website. Posting data (i.e., entering html in the textarea and pressing "Parse") produces this message:

"No options.node or options.html was provided and no document object could be found."

**Comment by Zegnat** [comment]
_Edit: .patch file removed. There is a PR: #3._

The problem is querystring not parsing the body correctly.

**Comment by btrem** [comment]
Is this work in an orphaned clone? Can you make it a PR on this repo?
