### ISSUE TITLE
Should we swap microformat-node for microformats-parser?

### ISSUE THREAD

**Issue by Zegnat** [microformats/microformats-parser-website-node#4]
Currently this page uses microformat-node ([npm](https://www.npmjs.com/package/microformat-node), [GitHub](https://github.com/glennjones/microformat-node)) instead of the newer [microformats-parser](https://microformats.github.io/microformats-parser/) ([npm](https://www.npmjs.com/package/microformats-parser), [GitHub](https://github.com/microformats/microformats-parser)).

There are a couple of advantages to the newer microformats-parser even apart from just being newer. Such as using [the standardised test suite](https://github.com/microformats/tests) and being owned by the [Microformats organisation on GitHub](https://github.com/microformats).

I am happy to do a PR for this, but are there any reasons why we would **not** want to switch?

**Comment by gRegorLove** [comment]
I'm not familiar with the current state of this, but there is also a fork of Glenn's microformat-node in this org: https://github.com/microformats/microformat-node

**Comment by Zegnat** [comment]
As far as I can tell, that fork has never been published to the npm Registry. So while there is a fork within the Microformats organisation it feels like it is more for historical purposes. When you install microformat-node from your standard Node/JavaScript package managers you will get the glennjones/microformat-node repo one.

**Comment by btrem** [comment]
I'm confused. If the "fork has never been published" why does it get installed in a standard pkg manager?

**Comment by Zegnat** [comment]
@btrem can you elaborate?

From what I can see, `npm install microformat-node` will install the copy from https://github.com/glennjones/microformat-node. The copy of the same code that is at https://github.com/microformats/microformat-node does not install from any package managers.

But I might well be mistaken. Let me know if you see other results from your package manager!

**Comment by btrem** [comment]
@Zegnat you are not mistaken; I was confused. After reading your reply (and re-reading your earlier comment), I now realize you were comparing the fork with its upstream original, and not comparing the glennjones parser with the newer microformats parser.

Sorry for the noise.
