### ISSUE TITLE
Document deployment/release process in README

### ISSUE THREAD

**Issue by aimee-gm** [microformats/microformats-parser-website-node#8]
The deployment process is as follows:

* The default branch is `next`. All PRs should target this branch.
* When ready to release, create a new branch from `next` named `release/x.y.z`
* Bump the version in `package.json` to `x.y.z`
* Merge the **release branch** to `main`. This will trigger the deployment.
* Merge `main` into `next`
* 🎉

**Comment by gRegorLove** [comment]
Note there's a pending PR adding a readme https://github.com/microformats/microformats-parser-website-node/pull/1

**Comment by aimee-gm** [comment]
Yep, I plan on reviewing that PR shortly
